달력형 페이지에 수정 디자인 반영
Buddies2024/spring pull request #158
Opened 2024-10-04 16:40 UTC by yeeuniii

## Work Description
> 달력형 페이지에 수정 디자인 반영

- 스프린트1 개념에 해당하는 부분만 디자인 반영했습니다. 
- 오른쪽 화살표 클릭시 미래의 날짜라면, 넘어가지 못하게 로직 추가했습니다.

## ISSUE
- closed #157 

## Screenshot
<img width="392" alt="Screenshot 2024-10-05 at 1 19 11 AM" src="https://github.com/user-attachments/assets/e6506c70-59f3-4161-a1c9-f74fb8ecdcd1">
<img width="396" alt="Screenshot 2024-10-05 at 1 18 45 AM" src="https://github.com/user-attachments/assets/6f8370ed-0b04-4ab7-b640-470aedaa177a">

## To Reviewers
- @redparkchu 오른쪽 화살표 처리 이런 식으로 해도 되는지 피드백 부탁드려용
- @naging @seungaeahn 수정된 디자인 반영 잘 되었는지 확인 부탁드려용

2024-10-06 05:57 UTC, redparkchu commented on server/src/main/resources/static/js/calendar-arrow.js
> +    }
return 을 통해 메소드를 종료시키고 있는것 같은데
제가 생각하는 return 은 함수내에서 데이터를 처리한 후 그 데이터를 함수외부로 꺼내고 싶을때 사용한다고 생각해요.
위와 같이 구현해도 상관없지만 한줄이라도 줄일 수 있다면 줄여보는건 어떨까요?

2024-10-06 06:00 UTC, redparkchu approved these changes
오늘이 속한 달에서 벗어나지 못하게 잘 구현했네요 👍 
미래로 갈수 없다면 해당 교환일기가 시작하기 전으로 못가게 구현하는건 어떤가요?

2024-10-06 06:04 UTC, redparkchu requested changes

2024-10-06 06:04 UTC, redparkchu commented on server/src/main/resources/static/js/calendar-arrow.js
> +}
파일 마지막줄에 개행을 추가시켜 주세요.

2024-10-06 09:35 UTC, yeeuniii commented
@redparkchu 그룹 생성 이전 시점의 달력형을 보지 못하게 하자는 의견 좋은 것 같습니다!
다만 아직 스프린트1 개념만이 사용된 페이지를 구성 중이기 때문에 그룹의 개념이 없습니다. 
스프린트2에 말씀하신대로 도입해보는 거 어떨가요?

2024-10-06 10:04 UTC, yeeuniii commented on server/src/main/resources/static/js/calendar-arrow.js
> +    }
의견에 동의합니다. 
하지만 빈 데이터를 return 을 하지 않고 어떻게 조건문을 확인하고 동작 처리를 막을 수 있을지 모르겠네요... 🥺
혹시나 의견이 있으시다면 방향성을 제시해주실 수 있나요?

2024-10-07 10:56 UTC, seungaeahn approved these changes

2024-10-07 12:57 UTC, redparkchu commented on server/src/main/resources/static/js/calendar-arrow.js
> +    }
if 문을 활용해 해당 조건이 참일경우 if 문 내부의 코드를 실행 시키는 방향으로 가는건 어떤가요?

2024-10-07 13:00 UTC, redparkchu commented on server/src/main/resources/static/js/calendar-arrow.js
> +    }
현재 이런 방식인거 같은데
```js 
if (예외 조건) {
    return;
}
메인 코드
``` 

대충 이런식으로 가는건 어떤가요?
```js 
if (!예외 조건) {
    메인 코드
}
```

2024-10-09 14:34 UTC, yeeuniii commented
@redparkchu 
피드백 반영 후, 타임리프 레이아웃 적용된 develop 브렌치 머지 완료하였습니다! 확인 부탁드려용

2024-10-10 10:28 UTC, redparkchu approved these changes
피드백 반영 잘했네요!
js 에서 사용된 이중 if 문은 나중에 제가 수정후 태그해서 보여드릴게요 😄

2024-10-10 12:14 UTC, merged