로그인 페이지 구현
Buddies2024/spring pull request #160
Opened 2024-10-04 16:51 UTC by yeeuniii

## Work Description
> 로그인 페이지 구현

- 로그인 페이지를 구현했습니다. 
- /login url로 접근하게 하기 위해 LoginController를 추가했습니다.

## ISSUE
- closed #129

## Screenshot
<img width="392" alt="Screenshot 2024-10-05 at 1 46 18 AM" src="https://github.com/user-attachments/assets/2584336e-bc64-4ee0-ada9-c24ca67df6f8">
<img width="392" alt="Screenshot 2024-10-05 at 1 50 29 AM" src="https://github.com/user-attachments/assets/3cf1c9cc-3f7e-4eaf-8db7-79471d001e63">

- 버튼 클릭시 오른쪽 페이지로 리다이렉트됩니다

## To Reviewers
@redparkchu 
- 처음 혼자서 하나의 페이지를 작성해보았는데 어떤지 피드백 부탁드려요!! 🤗
- html을 반환하는 컨트롤러 파일들을 하나의 폴더에서 관리하는 것도 괜찮을 것 같은데 어떤 거 같으신가요??

@naging @seungaeahn 
- 디자인 확인 부탁드려요~~

2024-10-06 06:02 UTC, redparkchu commented
@yeeuniii 
ui 폴더 안에 있는 Controller 파일들 말하는 건가요?

2024-10-06 06:13 UTC, redparkchu requested changes
혼자 구현하는거여서 힘들었을텐데 구현 잘했네요 💯

2024-10-06 06:13 UTC, redparkchu commented on server/src/main/resources/templates/login.html
> +</html>
파일 마지막엔 개행을 추가시켜 주세요.

2024-10-06 06:13 UTC, redparkchu commented on server/src/main/resources/templates/login.html
> +    <link rel="stylesheet" href="/css/fonts.css" type="text/css">
폰트 css 만든거 좋네요 👍

2024-10-06 09:14 UTC, yeeuniii commented
> @yeeuniii ui 폴더 안에 있는 Controller 파일들 말하는 건가요?

넵 api controller가 아닌, 서비스에서 실질적으로 노출되는 url과 관련된 controller를 말하는 것이었습니다!

2024-10-06 09:15 UTC, yeeuniii commented on server/src/main/resources/templates/login.html
> +</html>
넵!! 근데 파일 마지막에 개행을 추가해야하는 이유가 있나요?

2024-10-06 12:47 UTC, redparkchu commented on server/src/main/resources/templates/login.html
> +</html>
https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/
이걸 참고해보면 좋을거 같아요!

2024-10-06 13:00 UTC, redparkchu commented
@yeeuniii 
Exception 같은 경우에는 다른 기능들과 얽혀있는게 없기 때문에 하나의 폴더로 만들어서 관리하는게 좋다고 생각해요.
Exception 에서 에러가 발생하면 그 폴더에 들어가 어떤 오류인지 확인하면 쉽게 해결할 수 있을거에요.
그러나 컨트롤러 같은 경우앤 지금 diary 와 group 밖에 없는걸로 알고 있는데요.
컨트롤러와 해당 객체들은 서로 연결되어 있잖아요.
추후 더 많은 기능이 만들어지고 컨트롤러가 추가되면  group 컨트롤러에서 diary 값을 조회해야 하는 상황이 생길수도 있어요.
이런식으로 서로 얽히는 관계에선 비슷한 역할을 하는 객체 끼리 묶는것보단 비슷한 기능을 다루는 녀석들을 묶어서 관리하는게 더 유지보수 하기 편할거에요.

2024-10-09 13:56 UTC, seungaeahn approved these changes
확인했습니당!

2024-10-10 10:26 UTC, redparkchu approved these changes
피드백 반영 잘했네요! 💯

2024-10-10 12:15 UTC, merged