일기 API에 사용자, 그룹 도입. 테스트 코드 구현
Buddies2024/spring pull request #186
Opened 2024-10-10 18:04 UTC by jisunggi

## Work Description
> 달력형, 일기 작성 API에 사용자, 그룹 도입

- 일기엔티티에 사용자, 그룹 매핑
- 일기 작성시에 사용자, 그룹 일기에 추가 됨
- 달력형 조회 반환에 프로필 경로 추가 해 줌
- 일기 id 조회시 그룹 추가
- 달력형 api 테스트 코드
- 일기 작성 api 테스트 코드
- 일기 id 조회 api 테스트 코드

## ISSUE
- closed #111 

## Screenshot
- 일기 작성시에 사용자, 그룹 일기 엔티티에 추가해주었습니다
<img width="293" alt="스크린샷 2024-10-11 오전 2 56 42" src="https://github.com/user-attachments/assets/7ae16565-a2bb-49bf-bc8e-5e567c96f6b3">

- 월별형 조회 반환형 프로필 이미지도 추가 해주었습니다
<img width="492" alt="스크린샷 2024-10-11 오전 2 55 58" src="https://github.com/user-attachments/assets/8e907d06-100f-44a0-9be5-ca10b977ea02">

- 일기 작성 api, 월별형 조회 api 테스트 코드
<img width="381" alt="스크린샷 2024-10-11 오전 2 06 16" src="https://github.com/user-attachments/assets/424e7c04-5a5c-4842-85ad-4191f7698f0e">

2024-10-11 04:47 UTC, yeeuniii requested changes
테스트 코드를 이해한 게 보이는 테스트 코드네요 👍
이번에는 웃기지 않은 좋은 테스트 코드를 작성해주신 것 같아요!!
다만 조금 아쉬운 점은 API가 성공하는 경우 테스트만 보이네요. 
성공보다 실패의 경우의 수가 다양하고, 그에 대해서 서버에서 예외 처리가 잘 되었는지 파악하는 데에도 테스트 코드가 유용합니다! 한 번 실패 케이스에 대한 테스트도 작성해보는 거로 해봅시다!!

2024-10-11 04:47 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            Group group = groupRepository.findById(groupId).get();
사용자가 그룹에 속한 것을 확인했다고 가정하고 구현되어서 get 을 사용하신걸까요?

2024-10-11 04:47 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
> +                        diary.getCreatedAt().getDayOfMonth(), diary.getMember().getProfileLocation()))
매개변수가 모두 Diary 객체의 속성같은데, 그렇다면 Diary 하나만 매개변수로 넘기는 건 어떤가요?

2024-10-11 04:47 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +}
개행 추가해주세요

2024-10-11 04:47 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        assertThat(newDiary.getMember().getId()).isEqualTo(member.getId());
다른 속성들도 잘 저장되었는지 확인해보는 건 어떨까요?

2024-10-11 04:47 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        );
테스트 코드 깔끔하게 잘 구현됐네요 👍

2024-10-11 04:47 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
> +}
개행 추가해주세요

2024-10-12 07:59 UTC, jisunggi commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            Group group = groupRepository.findById(groupId).get();
넵 맞습니다!

2024-10-12 08:15 UTC, jisunggi commented
위의 피드백 반영하였고, 일기 id 조회 api 그룹 추가하였습니다.
각 api마다 실패의 경우에도 테스트 코드 추가하였습니다!
<img width="293" alt="스크린샷 2024-10-12 오후 5 14 42" src="https://github.com/user-attachments/assets/91bb07b8-71a4-4f66-bfa4-85a1573eb9f1">

2024-10-12 15:23 UTC, yeeuniii requested changes
성공뿐만 아닌 실패에 대한 테스트 추가 피드백 반영 좋네요! 앞으로는 구현하신 것보다 더 많은 경우에 대해서 생각해보시고 추가해주시면 더 좋은 테스트 코드가 될 것 같아요! 
추가로 구현 요청한 테스트 추가되면 다시 리뷰 요청해주세요!!

2024-10-12 15:23 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
> +    List<Diary> findByAllGroupYearAndMonth(Long groupId, int year, int month);
`findAll` ~ 로 바꿔주실 수 있을까요??

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        System.out.println(newDiary.getContent());
확인을 위한 코드인가요? 테스트와 연관없다면 제거 부탁드려용

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +
사진 없이 일기 작성하는 경우도 테스트해볼 수 있지 않을까요?

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
> +
실패의 경우로 쿼리 스트링이 비어있거나, 형식이 비어있거나, 존재하지 않는 날짜에 대한 테스트도 해볼 수 있을 거 같아용

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
> +
앞의 두 가지는 validation에 의해 되는 것을 다른 테스트를 통해서 확인한 경험이 있다면 따로 구현하지 않아도 괜찮겠지만 사소한 것에 대해서도 테스트를 만드는 것이 중요하다고 생각해용.
그리고 날짜 유효성 여부는 저희가 따로 로직을 처리해주는 것으로 알고 있는데 이러한 부분은 테스트가 필요해보이네요.

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
> +        groupRepository.saveAll(Arrays.asList(group, otherGroup));
group 객체는 왜 두번 save하나요?

2024-10-12 15:23 UTC, yeeuniii commented on server/src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
> +    void 달력형_일기_조회_실패() {
왜 실패하는지에 대한 설명을 추가하면 좋을 거 같아요

2024-10-12 18:01 UTC, jisunggi commented on server/src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
> +        groupRepository.saveAll(Arrays.asList(group, otherGroup));
삭제해주겠습니다!

2024-10-12 18:02 UTC, jisunggi commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +
이  경우 테스트하여 버그를 잡을 수 있었어요. 감사합니다!

2024-10-12 18:02 UTC, jisunggi commented on server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        System.out.println(newDiary.getContent());
삭제해주겠습니다!

2024-10-12 18:10 UTC, jisunggi commented
피드백 반영 하였고, 테스트코드도 더 다양한 경우의 수 추가 해주었습니다!
인터셉터에서 memberId 로 넘겨준 후, 서비스단의 메소드를 이용하여 member 객체를 확인하는 작업이 수정이 안되어있어서 수정해주었습니다. 일기 id 조회 api 는 groupId 를 이용하여 디비에 접근하여 해당 그룹에 일기가 없는 경우 diaryNotfound 예외 처리를 해주고 있어서 따로 그룹이 존재하는지 확인하는 코드는 추가하지 않았습니다. 피드백 부탁드릴게요!!
<img width="363" alt="스크린샷 2024-10-13 오전 3 00 35" src="https://github.com/user-attachments/assets/fd1c0b10-a75d-43c0-825c-e0f026933e54">

2024-10-13 06:08 UTC, yeeuniii reviewed
save 이후 멤버와 그룹을 넣어도 일기 테이블에 두 속성이 잘 저장되는건가요? 테스트를 보니 잘 동작하는 것처럼 보여서요! 이해가 잘 안되는데 설명해주실 수 있나요?

2024-10-13 06:08 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            diary.addMemberAndGroup(member, group);
member와 group을 넣은 후 save해야하는 거 아닌가요?

2024-10-13 06:08 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            diary.addMemberAndGroup(member, group);
여기도 위와 동일한 이슈인거같아요

2024-10-13 07:33 UTC, jisunggi commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            diary.addMemberAndGroup(member, group);
JPA에서 save()를 호출하는 시점에 diary는 영속 상태로 전환 됩니다. 영속 상태의 엔티티는 JPA가 관리하므로, 이후에 해당 엔티티의 필드 값을 변경하면 JPA는 자동으로 변경 사항을 감지하여 하나의 트랜잭션이 끝날 때, diary 객체의 모든 변경 사항이 데이터베이스에 반영된다고 해요. 저도 몰랐던 사실을 배워갑니다! 👍

2024-10-13 07:35 UTC, yeeuniii commented on server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +            diary.addMemberAndGroup(member, group);
새로운 정보 알아가네요! 더 공부해야겠어요 🥺 감사합니당

2024-10-13 07:35 UTC, yeeuniii approved these changes

2024-10-13 07:41 UTC, merged