일기 작성 api Location 헤더 수정
Buddies2024/spring pull request #219
Opened 2024-10-15 05:53 UTC by jisunggi

## Work Description
> 일기 api 에 그룹 도입으로 url 수정에 따라 일기 작성시에 로케이션 헤더에 url 수정해주었습니다

- 설명 1

## ISSUE
- closed #207 

## Screenshot
<img width="296" alt="스크린샷 2024-10-15 오후 2 52 44" src="https://github.com/user-attachments/assets/9e98620e-bac1-4d29-b68f-83bbf3b3ea6c">

2024-10-15 18:30 UTC, jisunggi commented
<img width="335" alt="스크린샷 2024-10-16 오전 3 30 01" src="https://github.com/user-attachments/assets/cd2d7c47-2c3a-472f-8f5c-242db50c6f03">
테스트코드 수정 후 결과입니다!

2024-10-15 18:48 UTC, yeeuniii requested changes
피드백 반영 부탁드려용

또한 제 피드백이 절대적으로 맞는게 아니므로 피드백에 대해 고민해보시고 그 고민의 결과를 코멘트로 남겨주셨으면 해요. 일방적인 피드백과 수용은 서로의 성장에도 좋지 않다고 생각합니다!

2024-10-15 18:48 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
> -                .header("Content-Location", "/diary/" + diaryId)
content-location 은 프론트와 상의 후 필요에 의해서 추가된 헤더입니다. 다시 추가 부탁드려요!
저는 location 헤더에 대한 필요성을 질문드린 것이었습니다.

2024-10-15 18:48 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>          assertThat(newDiary.getContent()).isEqualTo(data.get("content"));
어떤 방식으로 검증하고 있는건가요?

2024-10-16 08:23 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
> -                .header("Content-Location", "/diary/" + diaryId)
Content-Location 은 다시 추가 해주겠습니다! location 헤더에 일기 조회 api url 경로를 넣어놨었는데, 저희 서비스에는 일기 조회 api가  없으므로 저 경로 자체가 무의미한 값이라 생각 들어 삭제해주는 것이 맞다고 생각합니다.

2024-10-16 08:28 UTC, jisunggi commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>          assertThat(newDiary.getContent()).isEqualTo(data.get("content"));
location 헤더 경로에 있는 새로 만들어진 다이어리 id 값을 가져와 테스트 코드를 작성해 주었는데, Location 값이 사라지면서 새로운 다이어리 id를 추출해내는 방법에서 수정해주었습니다. 위의 방법은 일기들을 다 가져온 다음에 제일 최근에 만들어진 일기를 확인하는 방법입니다

2024-10-16 08:37 UTC, jisunggi commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>          assertThat(newDiary.getContent()).isEqualTo(data.get("content"));
content-location 을 다시 추가해줌으로써 위의 과정으로 새로운 다이어리 id 를 가져오는 방법보다는 기존방식과 비슷한 content- location 에서 diaryid 를 가져오는 방법으로 수정해주었습니다.

2024-10-16 08:38 UTC, jisunggi commented
<img width="355" alt="스크린샷 2024-10-16 오후 5 35 09" src="https://github.com/user-attachments/assets/89b467b7-530c-47d1-aace-62ae5e54d0cf">
수정 후 테스트 코드 결과입니다

2024-10-16 11:21 UTC, yeeuniii approved these changes
피드백 반영 잘 되었네요!! 고생하셨어요 😊

2024-10-16 11:45 UTC, merged