시작 페이지 구현
Buddies2024/spring pull request #228
Opened 2024-10-15 17:46 UTC by jisunggi

## Work Description
> 시작 페이지 구현

- 모든 경로에 대해서 토큰이 없는 경우, 로그인 페이지 전에 시작 페이지 띄움

## ISSUE
- closed #128 

## Screenshot
https://github.com/user-attachments/assets/5a2953fe-5a8c-4460-824d-cc26cdfe3003

## To Reviewers
시간은 제가 임의로 설정했는데 어떤지 확인 부탁드려요
많은 피드백 부탁드려요 😄

2024-10-15 18:53 UTC, yeeuniii requested changes
구현 잘 해주셨네요!!! 
애니메이션 마무리가 너무 급하게 되는 느낌이 있는 것 같아서 저는 시간 조금 더 늘려도 좋을 거 같아용

2024-10-15 18:53 UTC, yeeuniii commented on src/main/resources/static/css/start.css
> +}
개행 추가해주세요

2024-10-15 18:53 UTC, yeeuniii commented on src/main/resources/static/js/common/start.js
> +}, 2500);
개행 추가해주세요

2024-10-16 08:11 UTC, redparkchu approved these changes
피드백 다 반영했어요!

2024-10-16 09:09 UTC, jisunggi commented
gif 파일 보여준 후, png 파일 보여주는 작업 해주신부분 확인하였습니다.
파일 위치 변동 후, 로그인 페이지로 넘어가는 코드 주석 풀어주었습니다.
확인 후 승인 부탁드려요🙏

2024-10-16 09:48 UTC, yeeuniii approved these changes

2024-10-16 09:48 UTC, yeeuniii commented
피드백 반영 잘 되었네요!! 두 분 모두 고생 많으셨어요 👍👍

2024-10-16 10:04 UTC, merged