그룹원 간 일기 작성 순서 개념 반영
Buddies2024/spring pull request #262
Opened 2024-10-17 11:00 UTC by jisunggi

## Work Description
> 그룹원 간 일기 작성 순서 개념 반영

- 일기 작성 시 순서 변경
- 달력형 바텀 시트에 대한 API
- 일기 작성 시 순서 변경 테스트 코드
- 달력형 바텀 시트에 대한 API 테스트 코드

## ISSUE
- closed #217 

## Screenshot
- 일기 작성시 순서 확인 테스트 코드 결과
<img width="371" alt="스크린샷 2024-10-17 오후 7 57 19" src="https://github.com/user-attachments/assets/45cd56ae-f7a0-4ab7-b55a-b2ce3b74ad42">

- 바텀시트 api 테스트 코드 결과
<img width="368" alt="스크린샷 2024-10-17 오후 7 59 05" src="https://github.com/user-attachments/assets/6953c278-b754-42c0-a92a-f88f0982cbae">

## To Reviewers
- 그룹 생성시에, currentOrder 1로 생성으로 변경 해주었습니다.
https://github.com/Buddies2024/spring/blob/c2b7b0ce8929ffc1ce60c3bade10bd81e314a421/src/main/java/com/exchangediary/group/domain/entity/Group.java#L41-L47

<순서 작성 넘기기>
📌현재순서 = 내 순서일 경우에만 일기 작성 가능 
3명일 경우
그룹 생성시, 맨 처음 현재순서 = 1
1 사람 작성 완료, 현재 순서 = 2
2 사람 작성 완료, 현재 순서 = 3
3 사람 작성 완료, 현재 순서 = 4 -> 1
현재 순서가 인원수보다 커지는 경우 1로 초기화 

이때 새로운 사람이 들어 올 경우?
-> 한 바퀴 돌고 마지막에 써야 함

<바텀시트 api> 
1. 내 순서인지, 아닌지 확인
 -> 현재순서 = 내 순서인지 확인
2. 오늘 작성된 일기 있는지, 아닌지 확인

2024-10-17 11:56 UTC, yeeuniii requested changes
궁금한 점이나, 수정했으면 좋겠는 부분 피드백 남겨놓았습니다.
또한 DiaryCreateApiTest는 위 3개와 아래 3개의 차이가 무엇인가요?

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +    private void setCurrentOrderOfGroup(Group group) {
change~ 네이밍은 어떤가요??

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +        Boolean writtenTodayDiary = checkTodayDiaryExistent(groupId);
boolean을 반환하는 함수 네이밍으로 check~는 적절하지 않은 것 같아요

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +        return false;
조건문을 반환해도 되지 않나요?

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +        return false;
이 부분도 한 줄로 나타낼 수 있을 것 같아보여요!

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +    public DiaryBottomSheetResponse viewBottomSheet(Long groupId, Long memberId) {
`바텀 시트를 본다`는 것이 일기가 하는 일인가요? 
`바텀 시트`라는 것이 저희 서비스의 ui적인 한 부분인데 `viewBottomSheet` 와 `DiaryBottomSheeteReponse` 라는 네이밍이 적절한가 의문이네요 🤔

2024-10-17 11:56 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
> +    @GetMapping("/summary")
이 url을 통해 일기 요약을 조회할 수 있는 건가요?

2024-10-17 11:56 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>      void 일기_작성_성공() throws JsonProcessingException {
성공 여부를 사용자의 순서로 판단하고 있나요??

2024-10-17 11:56 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>      void 일기_작성_성공() throws JsonProcessingException {
아 이 부분은 구현되지 않은 것으로 보이네요.
사용자의 순서 일기를 작성할 수 있는 순서임을 가정하고 현재 구현된건가요?

2024-10-17 11:56 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +    @Test
아래 테스트부터는 어떤 테스트인가요?

2024-10-17 15:08 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
> +    @GetMapping("/summary")
/status 로 변경해주겠습니다!

2024-10-17 15:09 UTC, jisunggi commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>      void 일기_작성_성공() throws JsonProcessingException {
네! 일기를 쓸 수 있는 상태인지 확인하는 건 일기 작성 인가가 구현된 후 테스트 코드에 추가 해주어야 할 것 같아 현재는 추가 안되어있습니당

2024-10-17 15:16 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +    public DiaryBottomSheetResponse viewBottomSheet(Long groupId, Long memberId) {
저도 이부분이 조금 의문이 들었었는데 지적해주셔서 감사합니다! 고민해본 결과 getDiaryWritable, DiaryWritableResponse 로 변경하겠습니다.

2024-10-17 15:26 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
> +        Boolean writtenTodayDiary = checkTodayDiaryExistent(groupId);
is~ 로 수정 해주었습니다

2024-10-17 17:14 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +    @Test
`@DisplayName` 어노테이션 사용해서 어떤 테스트인지 설명을 추가해주시면 좋을 것 같아요

2024-10-17 17:27 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
>      void 일기_작성_성공() throws JsonProcessingException {
일기 작성 인가가 언제 구현될 지 모르니 지금 간단하게라도 구현해주시면 좋을 거 같네요 😊

2024-10-17 18:26 UTC, yeeuniii requested changes
피드백 반영 잘 되었네요!! 
아까 디코에서 이야기한 일기 작성 인가 부분 간단하게 추가 부탁드려요!!

2024-10-18 05:21 UTC, yeeuniii approved these changes

2024-10-18 05:23 UTC, yeeuniii commented
마지막 커밋에서 테스트코드에 인가 확인 테스트가 추가된건가요?
인가 코드 추가 후 테스트코드에 어떤 부분이 변경되었다는건가요?

2024-10-18 05:50 UTC, yeeuniii commented
@jisunggi 
임시로 추가해주신 일기 작성 인가에 대해서 403 Forbidden을 응답하도록 수정했습니다. 
또한 예외 핸들러에서 ServiceException을 상속받고 있는 예외에 대한 처리 코드가 똑같아서 ServiceException에 대한 예외 핸들러 하나로 통일시켰습니다. 이렇게 ServiceException에 대한 핸들러를 하나 만들어 놓으면, 추후 ServiceException를 상속받는 예외 클래스가 추가되어도 핸들러를 추가하지 않아도 된다는 이점이 존재할 것 같습니다.

2024-10-18 15:34 UTC, merged