일기 작성시, 이미지 크기와 형식 예외 처리
Buddies2024/spring pull request #265
Opened 2024-10-17 15:04 UTC by jisunggi

## Work Description
> 일기 작성시, 이미지 크기와 형식 예외 처리

- 이미지 크기 확인
- 이미지 형식 확인

## ISSUE
- closed #263 

## Screenshot
- 이미지 형식 확인 테스트 코드
<img width="326" alt="스크린샷 2024-10-17 오후 11 58 29" src="https://github.com/user-attachments/assets/63574ffd-88dd-401e-85eb-79aec8caddcd">

-이미지 크기 확인
<img width="400" alt="스크린샷 2024-10-17 오후 11 56 27" src="https://github.com/user-attachments/assets/21566b3f-8864-4676-ab23-917fc7e10a1a">
<img width="247" alt="스크린샷 2024-10-17 오후 11 56 47" src="https://github.com/user-attachments/assets/53470c98-01c0-47bb-b805-731abed46487">

## To Reviewers
이미지 용량이 큰 파일을 깃에 올리는 건 적절하지 않은 것 같아, 테스트코드 대신 포스트맨으로 api 예외처리 확인 해주었습니다.

2024-10-17 17:24 UTC, yeeuniii requested changes
큰 이미지에 대해서 따로 처리해주신 점 좋네요!! 💯💯
로직 상으로는 큰 문제 없어보여요! 잘 구현해주셨네용
약간의 리팩터링이 더해진다면 찐백점 코드가 될 것 같아요~ 피드백 남겼으니 확인해주세요!!

2024-10-17 17:24 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +        long maxSizeInBytes = 5 * 1024 * 1024;
max-size를 설정파일에서 설정해주는 것으로 알고 있는데,
`@Value` 어노테이션을 사용하여 유동적으로 크기를 지정할 수 있지 않을까요?

2024-10-17 17:24 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +        if (file.getSize() >= maxSizeInBytes) {
크기가 똑같아도 안되나요??

2024-10-17 17:24 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +                "image/heif".equals(contentType);
지원 이미지 확장자들을 static 배열로 만들어서 사용하는 건 어떨까요?
그렇게된다면 stream 이나 foreach문을 사용하여 코드를 간결하게 만들 수도 있을 것 같아요!!

2024-10-17 17:24 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(apiErrorResponse, status);
저희 컨트롤러에서 반환하는 방식과 동일한 형식을 사용하면 어떨까요?

2024-10-17 17:24 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(apiErrorResponse, status);
status를 꼭 조건문으로 사용해야 하나요? ErrorCode의 status를 반환하면 안되나요?

2024-10-17 17:24 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        String jsonData = objectMapper.writeValueAsString(data);
이 부분은 뭔가요?

2024-10-17 17:39 UTC, jisunggi commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        String jsonData = objectMapper.writeValueAsString(data);
멀티파트 데이터에 json data를 map 으로 만들어서 넣어주는 과정입니다!

2024-10-17 17:53 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +        if (file.getSize() >= maxSizeInBytes) {
안전하게 똑같은 파일까지 안되게 처리 해놨습니다!

2024-10-17 18:28 UTC, yeeuniii commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        String jsonData = objectMapper.writeValueAsString(data);
함수로 빼도 좋을 거 같네요!

2024-10-18 05:32 UTC, yeeuniii requested changes
피드백 확인 부탁드려요~

2024-10-18 05:32 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +    );
상수 선언은 클래스 상단에서 해주세요.

2024-10-18 05:32 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +        if (!VALID_IMAGE_TYPES.contains(contentType)) {
이미지 타입보다는 이미지 형식이라고 많이 이야기하지 않나요?? 
[이미지 파일 형식](https://ko.wikipedia.org/wiki/%EC%9D%B4%EB%AF%B8%EC%A7%80_%ED%8C%8C%EC%9D%BC_%ED%98%95%EC%8B%9D)

2024-10-18 05:32 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +    );
자료구조로 Set을 사용하신 이유가 있나요??

2024-10-21 11:39 UTC, jisunggi commented on src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
> +        String jsonData = objectMapper.writeValueAsString(data);
더 코드의 가독성이 좋을 것 같아 따로 빼주었습니다. 감사합니다!

2024-10-21 12:04 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +    );
set은 중복 저장이 안되기 때문에 중복 값이 없는 경우, 시간복잡도가 낮아 특정값만 빠르게 확인 할 수 있는 경우에 사용하는 것이 맞다고 생각하여 사용해주었습니다!

2024-10-21 13:17 UTC, yeeuniii approved these changes
컨벤션 관련해서 피드백 남겼으니, 이 부분 반영하고 머지하면 될 것 같네용!

2024-10-21 13:17 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
> +    );
상수는 보통 클래스 최상단에 위치해요!

2024-10-21 13:17 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
>      private void validateImageType(MultipartFile file) {
메서드 간 개행 추가해주세요

2024-10-21 14:01 UTC, merged