그룹 나가기 api 구현
Buddies2024/spring pull request #279
Opened 2024-10-21 20:39 UTC by jisunggi

## Work Description
> 그룹 나가기 api 구현

## ISSUE
- closed #243 

## Screenshot
<img width="372" alt="스크린샷 2024-10-22 오전 5 27 59" src="https://github.com/user-attachments/assets/f323235c-bb2d-4bde-a516-9b8da808e31e">

2024-10-22 03:00 UTC, yeeuniii requested changes
아직 api가 그룹 나가기 기능이 실행될 때의 작업이 모두 구현되지 않은 것처럼 보여요.
해당 api 안에서 어떤 작업이 되어야하는지 다시 생각해보시고 리뷰 재요청 부탁드려요.

2024-10-22 18:30 UTC, jisunggi commented on src/main/java/com/exchangediary/group/ui/ApiGroupController.java
> +    @PatchMapping("{groupId}/leave")
수정하는쪽이 더 가까운 것 같아 patch로 통일 시켰습니다!

2024-10-22 18:31 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +        memberRepository.save(member);
나머지 기능들 추가 구현해주었습니다.

2024-10-22 18:32 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +public class GroupLeaveService {
쿼리 서비스에 포함시키는 것보다 같은 patch 메소드를 사용하는 그룹 가입 서비스와 동일하게 단일 서비스로 가는게 맞다고 생각하였습니다.

2024-10-23 05:27 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +                .filter(m -> m.getOrderInGroup() > orderInGroup)
m이 아닌 member로 네이밍을 하는 건 어떨까요?

2024-10-23 05:48 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>          memberRepository.save(member);
흐름상 멤버를 먼저 탈퇴시키고, 남은 그룹원의 순서를 업데이트시키는 식으로 구성되는 건 어떤가요?

2024-10-23 18:14 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +                .filter(m -> m.getOrderInGroup() > orderInGroup)
좋은 것 같아요!! 수정하겠습니다😄

2024-10-23 18:15 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>          memberRepository.save(member);
member의 순서를 updateOrderOfMembers 에서 사용하고 있어서 더 먼저 처리해주었는데 따로 저장해두고 그 값을 사용하는게 더 나을까요?

2024-10-23 18:21 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>          memberRepository.save(member);
제가 하고싶은 방법대로 하려면 그렇게 되어야겠네요! 
실제 동작되는 로직과 동일하게 메서드 구성을 하면 어떨까해서 메서드 호출 순서를 바꾸면 어떨까 했어요.
어떤 방법이 더 좋을지 지성님이 생각해보시고 구현해주시면 될 것 같아요!!

2024-10-24 05:55 UTC, yeeuniii reviewed
로직이 정상적으로 작동하는 것 같네요!
그룹원들의 순서 업데이트하는 부분의 코드를 충분히 리팩터링할 수 있어 보여서 몇가지 코멘트 남겨보았어요! 리팩터링의 필요성을 생각해보시고, 리뷰 재요청 부탁드려요~

2024-10-24 05:55 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>          }
오버로딩하지 않은 updateCurrentOrder을 사용해서 if-else로 경우를 나누지 않고 하나로 해결할 수 있지 않나요??

2024-10-24 05:55 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +    }
filter를 거친 후 map을 사용해서 탈퇴하려는 사용자보다 뒷 순서 멤버들의 순서를 1 줄여줘도 되지 않을까요?

2024-10-24 05:55 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +        largerOrderMembers.forEach(member -> member.updateOrderInGroup(member.getOrderInGroup() - 1));
map을 사용해서 처리한다면 이렇게 따로 반복문을 돌리지 않아도 되지 않을까요?

2024-10-24 09:41 UTC, jisunggi commented
위에 말씀주신 토대로 리팩토링 한 후 결과입니다!
<img width="802" alt="스크린샷 2024-10-24 오후 6 30 11" src="https://github.com/user-attachments/assets/06e922d3-f7fc-4e70-ad35-f7d033f2df0c">
<img width="355" alt="스크린샷 2024-10-24 오후 6 30 18" src="https://github.com/user-attachments/assets/042b9a93-a73f-4c1a-af9e-e2b907bed177">

2024-10-24 09:49 UTC, yeeuniii approved these changes
여러 번의 리뷰와 피드백이 있었는데, 이제 진짜 머지해도 될 것 같네요!!
고생 많으셨어요 👍 (( 저두 ㅎㅎ
컨벤션과 네이밍 관련해서 피드백 남겼으니, 컨벤션은 일치시켜주시고 네이밍은 생각해보시고 피드백 반영 부탁드려요!

2024-10-24 09:49 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +            group.updateCurrentOrder(currentOrder,members.size() - 1);
매개변수 간 띄어쓰기 추가해주세요.

2024-10-24 09:49 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +    private void updateCurrentOrder(Group group, int orderInGroup) {
updateGroupCurrentOrder은 어떨까요? 
지금 순서와 관련된 것들이 많이 바뀌어서 메서드명을 조금 더 구체적으로 써주면 나중에 코드 읽을때 좋을거 같아용

2024-10-24 09:49 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>      private void updateOrderOfMembers(Group group, int orderInGroup) {
updateGroupMembersOrder는 어떤가요?? of 가 없어도 괜찮을거같아요!!

2024-10-24 09:55 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
> +            group.updateCurrentOrder(currentOrder,members.size() - 1);
감사합니다!

2024-10-24 09:55 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaveService.java
>      private void updateOrderOfMembers(Group group, int orderInGroup) {
더 나은 것 같아 수정했습니다!!

2024-10-24 09:58 UTC, merged