그룹원 강퇴 API 구현
Buddies2024/spring pull request #286
Opened 2024-10-22 19:42 UTC by jisunggi

## Work Description
> 그룹원 강퇴 API 구현

- 강퇴 시킬 멤버의 닉네임을 받아 온 후, 그룹 나가기 서비스를 이용해 구현하였습니다
(방장 인가는 통과했다는 가정하에 구현)

## ISSUE
- closed #241 

## Screenshot
<img width="301" alt="스크린샷 2024-10-23 오전 4 41 39" src="https://github.com/user-attachments/assets/f352f390-cb45-4acf-82d7-a3fef5b4af60">

2024-10-23 05:51 UTC, yeeuniii requested changes
그룹 나가기 API 피드백 반영하고 해당 API도 재작업해서 다시 리뷰 요청 부탁드려요.

2024-10-25 06:32 UTC, yeeuniii requested changes
피드백 반영 후 재요청 부탁드려용

2024-10-25 06:32 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupLeaderService.java
> +        Optional<Member> member = memberRepository.findByNickname(request.nickname());
그룹이 일치하는지도 확인해야할 것 같아요

2024-10-25 08:25 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupLeaderService.java
> +        Optional<Member> member = memberRepository.findByNickname(request.nickname());
findMemberByNickname 메소드를 이용하는 방법으로 수정했습니다!

2024-10-25 08:57 UTC, yeeuniii approved these changes
기능 구현 잘 된 것 같네요!! 머지해도 될 것 같아요 💯

2024-10-25 09:08 UTC, merged