그룹 멤버인지 인가 인터셉터 구현
Buddies2024/spring pull request #309
Opened 2024-10-25 17:09 UTC by jisunggi

## Work Description
> 그룹 멤버인지 인가 인터셉터 구현 

## ISSUE
- closed #180 

## Screenshot
<img width="404" alt="스크린샷 2024-10-26 오전 2 06 07" src="https://github.com/user-attachments/assets/c173c1b1-ec6e-4596-8be2-797fc487537f">

## To Reviewers

2024-10-25 17:29 UTC, yeeuniii requested changes
여러 케이스에 대해서 테스트를 잘 작성해주셨네요!! 
로직상 잘못된 부분은 없어보이지만, 리팩터링하면 더 좋은 코드가 될 것 같아요!

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/config/web/WebConfig.java
> +                .excludePathPatterns("/group");
/group/** 에 /group도 들어가는 게 맞나요??

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +    public boolean isMemberinGroup(Long memberId, Long groupId) {
네이밍 대소문자 이상해요

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +    public boolean isMemberinGroup(Long memberId, Long groupId) {
사용자가 매개변수로 넘어간 그룹에 속하는 지를 확인하는 메서드인 것 같은데, 메서드명이 그 뜻을 직관적으로 나타내고 있지 못 한 것 같아요.

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +        Optional<GroupId> optionalGroupId = memberRepository.findGroupIdById(memberId);
optional 이라는 클래스명을 변수 네이밍에 포함시킨 이유가 있을까요?

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +        if (optionalGroupId.isEmpty() || !optionalGroupId.get().groupId().equals(groupId)) {
가독성이 그리 좋지 않은 코드같아보이는데요.. 리팩터링해보면 좋을 것 같아요!

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +        if (optionalGroupId.isEmpty() || !optionalGroupId.get().groupId().equals(groupId)) {
또한 equals를 사용할 때에는 확실히 null이 되지않을 값에서 호출하는 건 어떤가요?? NPE를 방지할 수 있을 것 같아요!!

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +            memberQueryService.isMemberinGroup(memberId, groupId);
boolean 값을 반환해서 사용되지 않고 있는 것 같은데, 그렇다면 boolean을 반환하는 이유가 있나요?
사용자가 groupId에 해당하는 그룹에 포함되는지 확인하는 메서드로 만들어도 되는 거 아닌가요?

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +            Optional<Long> authorizedGroupId = memberQueryService.findGroupBelongTo(memberId);
이렇게 네이밍하신 이유가 있을까요?

2024-10-25 17:29 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +                throw exception;
저는 api 요청인지 판단할 때 contains 메서드를 사용했는데, startsWith 메서드가 더 정확해보이네요!! 하나 알아갑니다 👍👍

2024-10-25 18:10 UTC, jisunggi commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +            memberQueryService.isMemberinGroup(memberId, groupId);
void형으로 반환해주고, checkMemberOfGroup 이름으로 변경해주었습니다!

2024-10-25 18:10 UTC, jisunggi commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +        if (optionalGroupId.isEmpty() || !optionalGroupId.get().groupId().equals(groupId)) {
좋은 방법인 것 같아요!! 리팩토링 해보았습니다👍

2024-10-25 18:13 UTC, jisunggi commented on src/main/java/com/exchangediary/member/service/MemberQueryService.java
> +        Optional<GroupId> optionalGroupId = memberRepository.findGroupIdById(memberId);
optinal 클래스로 감싸져있는 변수라고 생각해서 지어주었는데, 이 변수는 필요 없을 것 같아 삭제해주었습니다.

2024-10-25 18:16 UTC, jisunggi commented on src/main/java/com/exchangediary/global/config/web/WebConfig.java
> +                .excludePathPatterns("/group");
제가 확인한 결과, 이 url 이랑 뒤에 있는 /api/groups 도 같이 포함되었습니다. 그래서 두 url 은 따로 빼주었어요!

2024-10-25 18:18 UTC, jisunggi commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +            Optional<Long> authorizedGroupId = memberQueryService.findGroupBelongTo(memberId);
url groupId 값이 아닌 옳은 url로 가기위해 인가된 groupId 라는 뜻을 주고싶어서 이렇게 네이밍했습니다!

2024-10-25 18:20 UTC, jisunggi commented
<img width="434" alt="스크린샷 2024-10-26 오전 3 19 38" src="https://github.com/user-attachments/assets/1a6a151e-a472-450a-9828-f1dd674facc0">
피드백 반영 후, 모든 테스트 결과입니다!

2024-10-26 05:27 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
> +            Optional<Long> authorizedGroupId = memberQueryService.findGroupBelongTo(memberId);
그룹 인가는 이 인터셉터에서 진행되는 것으로 알고 있는데요.
위 groupId가 인가된 그룹 아이디인 것인가요?

2024-10-26 07:57 UTC, yeeuniii approved these changes
그룹 인가 인터셉터에서 설정해주신 groupId 일기 조회, 작성 인터셉터에서 받아서 사용하도록 수정해주고, 리팩터링 진행해주었습니다. 머지하도록 하겠습니다~

2024-10-26 07:57 UTC, merged