일기 작성, 조회 API 수정
Buddies2024/spring pull request #358
Opened 2024-11-01 10:46 UTC by jisunggi

## Work Description
> 일기 작성, 조회 API 수정

- 일기 작성 api 페이지 별로 작성 가능하게 추가
- 일기 조회 api
- 사진 서버에 저장

- 일기 작성 테스트코드 수정 (사진 서버에 저장, 페이지 내용 저장 확인)
- 일기 조회 테스트코드 구현

## ISSUE
- closed #351
- closed #350 
- closed #349 

## Screenshot
<img width="321" alt="스크린샷 2024-11-01 오후 7 40 48" src="https://github.com/user-attachments/assets/dac2bc8a-fbc4-43f3-9880-8f06f861845c">
일기 테스트 결과입니다

## To Reviewers
DiaryContentDto 이름이 적절하지 않은 것 같은데 DiaryContent 는 엔티티와 겹치는 이슈때문에 하지 못했습니다. 다른 네이밍 의견 있으면 말씀 주세요🤗

2024-11-01 12:10 UTC, yeeuniii requested changes
일기 조회 페이지에서 변하지 않는 부분(생성일, 오늘의 기분)은 충분히 타임리프 모델로 처리 가능하고, 이렇게 사용하기 위해서 #352 이슈를 처리한 것도 있습니다. 프론트와 이야기 후, 이 부분은 타임리프 모델로 처리 가능하도록 변경 부탁드려요!!
또한 viewDiary API에서 사용되지 않는 매개변수가 보이는데 제거 부탁드립니다.
코멘트에 남겨놓았듯이 dto의 사용이 혼동되고 있는것 같은데 분리 부탁드려요!

2024-11-01 12:10 UTC, yeeuniii commented on src/test/resources/truncate.sql
>  TRUNCATE TABLE `group`;
새로 추가된 테이블 truncate 쿼리 추가해주세요

2024-11-01 12:10 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/domain/entity/Diary.java
> +    private List<DiaryContent> contents;
diary에 content가 없어도 되나요?

2024-11-01 12:10 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
> +    private static List<DiaryContentDto> getDiaryContent(List<DiaryContent> diaryContents) {
DiaryContentDto를 request, response에서 모두 쓰이나요?
API에 변동이 생길 수도 있어 dto는 보통 api의 요청/응답에 따라서 분리해서 많이 사용합니다.
요청과 응답 dto를 분리해보는 거 어떨까요?

2024-11-01 17:30 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/domain/entity/Diary.java
> +    }
upload로 지어주었습니다!

2024-11-01 17:41 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
> +                    + diary.getGroup().getId();
그룹 아이디를 넘겨받는 걸로 수정해주었습니다~!

2024-11-01 18:11 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
> +                .toList();
while 로 바꾼 코드가 훨씬 명확하고 좋은 것 같아요!!🤩

2024-11-01 18:16 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
> +            file.transferTo(new File(imageLocation));
imageLocation 변수를 따로 할당하지 않는 것으로 수정해주었습니다!
transferTo 메서드는 Spring의 MultipartFile 인터페이스에서 제공해주는 메소드인데, 파일을 메모리에서 지정된 위치로 직접 복사하여 파일을 저장하는 방식으로 저장합니다.

[MultipartFile 이미지 업로드](https://velog.io/@dani0817/Spring-%ED%8C%8C%EC%9D%BC%EC%97%85%EB%A1%9C%EB%93%9CMultipartFile)

2024-11-01 18:41 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/domain/entity/Diary.java
> +    private List<DiaryContent> contents;
diaryContent를 생성할때 diaryId 가 필요해서 diary를 먼저 content 없이 생성하고, 그 diaryId 를 이용하여 diaryContent를 추가하는 방식이 맞으니 지금상태가 맞는 것 같아요! 마찬가지로 저희 서비스에서는 그룹에 member 가 없을 경우는 없지만 그룹을 생성하고 member를 나중에 추가하는 방식이라 @NotNull 어노테이션을 사용하지 않은 것 처럼요! 어떻게 생각하시나요?

2024-11-01 18:47 UTC, jisunggi commented
<img width="325" alt="스크린샷 2024-11-02 오전 3 46 46" src="https://github.com/user-attachments/assets/fe12a246-d031-42b4-a0ad-708264bb430c">
모든 테스트 결과입니다!
일기 작성시에 이미지가 서버에 저장되는 테스트 코드는 삭제해주었습니다

2024-11-02 00:09 UTC, yeeuniii approved these changes
머지해도 될 것 같네요! 고생 많으셨어요 👍

2024-11-02 00:09 UTC, yeeuniii commented on src/main/java/com/exchangediary/diary/ui/dto/request/DiaryContentRequest.java
> +        String content
notnull 어노테이션 추가하는 거 어떨까요?

2024-11-02 04:57 UTC, jisunggi commented on src/main/java/com/exchangediary/diary/ui/dto/request/DiaryContentRequest.java
> +        String content
추가해주었습니다!!

2024-11-02 04:57 UTC, merged