답글 등록 API
Buddies2024/spring pull request #373
Opened 2024-11-08 15:14 UTC by jisunggi

## Work Description
> 답글 등록 API

- reply 앤티티 생성
- 답글 등록 구현

## ISSUE
- closed #367 

## Screenshot
<img width="281" alt="스크린샷 2024-11-09 오전 12 12 05" src="https://github.com/user-attachments/assets/d13ad02c-c016-4822-af00-2cf4ee75bc71">

2024-11-08 15:57 UTC, yeeuniii requested changes
전체적으로 잘 구현되었네요!! 사소하게 수정해야할 부분들 피드백 남겨놓았으니 반영 부탁드려요~

2024-11-08 15:57 UTC, yeeuniii commented on src/main/java/com/exchangediary/reply/domain/entity/Reply.java
> +public class Reply {
BaseEntity 상속!!

2024-11-08 15:57 UTC, yeeuniii commented on src/main/java/com/exchangediary/reply/domain/entity/Reply.java
> +    private final String content;
LongVarchar 타입으로 설정하신 이유가 있을까요?

2024-11-08 15:57 UTC, yeeuniii commented on src/main/java/com/exchangediary/reply/ui/ApiReplyController.java
> +public class ApiReplyController {
reply 컨트롤러를 따로 만들어준 이유가 있나요?

2024-11-08 15:57 UTC, yeeuniii commented on src/main/java/com/exchangediary/reply/service/ReplyCreateService.java
> +        diaryAuthorizationService.checkDiaryViewable(member, diary);
댓글 인가 이후에 comment를 찾아도 되지 않을까요?

2024-11-08 15:57 UTC, yeeuniii commented on src/main/java/com/exchangediary/global/exception/ErrorCode.java
> +    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "일기를 찾을 수 없습니다."),
메시지 수정해야할 것 같아용

2024-11-18 10:21 UTC, jisunggi commented on src/main/java/com/exchangediary/reply/ui/ApiReplyController.java
> +public class ApiReplyController {
reply 도메인을 따로 빼면서 컨트롤러도 따로 만들어주었는데 comment 패키지에 다 합쳐주는게 더 나을까요?

2024-11-18 10:24 UTC, jisunggi commented on src/main/java/com/exchangediary/reply/domain/entity/Reply.java
> +    private final String content;
답글에 글자 수 제한이 없다보니 더 많이 저장할 수 있는 LongVarchar로 설정해주었습니다.

2024-11-18 10:25 UTC, jisunggi commented on src/main/java/com/exchangediary/reply/service/ReplyCreateService.java
> +        diaryAuthorizationService.checkDiaryViewable(member, diary);
그 방법이 더 좋은 것 같아요! 감사합니다

2024-11-20 18:33 UTC, jisunggi commented
<img width="262" alt="스크린샷 2024-11-21 오전 3 31 20" src="https://github.com/user-attachments/assets/b4da69bb-a5fb-497e-82fb-43945e06edb4">
<img width="600" alt="스크린샷 2024-11-21 오전 3 32 01" src="https://github.com/user-attachments/assets/90b669eb-dd7d-45e1-88b5-220e7b099699">

테스트 결과, reply 테이블 생성 결과입니다

2024-11-21 02:51 UTC, yeeuniii reviewed
https://github.com/Buddies2024/spring/pull/373#discussion_r1834627093

마지막 피드백(에러코드 메시지 수정) 반영된건가요??

2024-11-21 02:51 UTC, yeeuniii commented on src/main/resources/db/migration/V3.1__create_reply.sql
> +)
개행 추가해주세요

2024-11-21 05:25 UTC, jisunggi commented on src/main/resources/db/migration/V3.1__create_reply.sql
> +)
추가했습니다! 감사합니다. 위에 말씀 주신 에러코드 메세지는 머지 후 충돌 해결하면서 수정해줬었서 커밋이 피드백 반영에 안 들어가 있네요🥲

2024-11-21 06:11 UTC, yeeuniii approved these changes

2024-11-21 06:23 UTC, merged