그룹 코드 수정
Buddies2024/spring pull request #380
Opened 2024-11-10 08:36 UTC by jisunggi

## Work Description
> 그룹 코드 수정

- group_id 생성 전략 수정
- 그룹 코드 groupId로 확인
- 프론트 그룹 코드 복사하는 내용 그룹 id로 수정

## ISSUE
- closed #378

## Screenshot
<img width="305" alt="스크린샷 2024-11-10 오후 5 35 15" src="https://github.com/user-attachments/assets/98157d5d-9209-4f87-82be-650491e20fd6">

## Reference
[custom Id @GenericGenerator](https://clipcode.tistory.com/58)
[Jpa Hibernate Custom Id Generator 와 예제](https://0soo.tistory.com/177)

2024-11-10 10:58 UTC, yeeuniii requested changes
그룹 아이디가 쓰이던 곳이 많았어서, 타입 자체를 바꾼다는게 굉장히 볼륨있는 작업이었는데 너무 잘해주신 것 같네요!! 고생 많으셨어요 👍👍
궁금한 점과, 수정됐으면 좋겠는 부분 피드백 남겼으니 반영 및 답변 부탁드려요!!

2024-11-10 10:58 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
> +}
개행 추가해주세요

2024-11-10 10:58 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
> +        return UUID.randomUUID().toString().substring(0, 8);
이렇게 id가 구현이 되면 중복되는 id가 생길 가능성은 없나요?

2024-11-10 10:58 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/domain/entity/Group.java
> +    public static Group of(String groupName) {
from 으로 함수명 변경부탁드려용

2024-11-10 10:58 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/ui/dto/response/GroupCreateResponse.java
>      public static GroupCreateResponse of(Group group) {
from으로 메서드명 수정 부탁드려용

2024-11-10 11:35 UTC, jisunggi commented on src/main/java/com/exchangediary/group/domain/entity/Group.java
> +    public static Group of(String groupName) {
감사합니다. 수정하겠습니다!

2024-11-10 11:56 UTC, jisunggi commented on src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
> +        return UUID.randomUUID().toString().substring(0, 8);
총 랜덤한 32자에서 앞 자리 8자를 잘라내서 만들어내는 방법이라 43억개의 조합이 가능하여 고유성은 높다고 생각해요! 아니면 현재 시간도 조합해서 똑같은 순간에 만들지 않은 이상 고유성을 더 높일 수 있습니다. 그럴 경우에는 지금 8자보다는 좀 늘려야 할 것 같아요.

2024-11-10 18:58 UTC, yeeuniii approved these changes
groupId가 중복되는 경우에 대한 테스트를 하나 구현해보면 좋을 거 같네요!
테스트 추가 후 머지 부탁드려요~

2024-11-10 18:58 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/service/GroupCreateService.java
> +                return groupRepository.saveAndFlush(group);
saveAndFlush는 어떤 메서드인가요?? save와 어떤 차이를 갖나요?

2024-11-10 20:03 UTC, jisunggi commented on src/main/java/com/exchangediary/group/service/GroupCreateService.java
> +                return groupRepository.saveAndFlush(group);
save메소드는 하나의 트랙잭션이 다 끝나고 데이터베이스에 반영되어 id 값이 중복되어도 예외를 잡아내지 못하고, while 문을 탈출 하는 오류가 있었습니다. 그래서 저장과 동시에 데이터베이스에 바로 반영하는 saveAndFlush 메소드를 사용하여 id 값이 중복되면 바로 예외 던져지게 해주었어요!

2024-11-11 06:09 UTC, merged

2025-02-22 09:01 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
> +        return UUID.randomUUID().toString().substring(0, 8);
지성님, UUID로 구성되는 문자가 숫자 + 알파벳 대소문자로 10 + 26 * 2 = 총 62개여서, 8자로 랜덤한 id를 생성할 경우 62의 8승으로 218,340,105,584,896, 즉 약 218조개라고 합니다.

2025-04-11 15:28 UTC, yeeuniii commented on src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
> +        return UUID.randomUUID().toString().substring(0, 8);
다시 서치해보니 UUID는 16진수로 구성된 값이었네요..! 
16 ^ 8 으로 약 43억개의 조합이 맞는 것 같습니다! 잘못된 정보 전달 죄송해요!!
[참고 포스팅](https://kingofbackend.tistory.com/173)