일기 작성 페이지 툴팁 박스 추가
Buddies2024/spring pull request #439
Opened 2024-12-10 18:37 UTC by jisunggi

## Work Description
> 일기 작성 페이지 툴팁 박스 추가

## ISSUE
- closed #438 

## Screenshot
<img width="250" alt="스크린샷 2024-12-11 오전 3 36 59" src="https://github.com/user-attachments/assets/04eb3a26-3559-41eb-b68c-f7fead754f86">

2024-12-11 12:54 UTC, yeeuniii requested changes
툴팁 안의 메시지는 팁 메시지가 추가될 가능성도 있으니 확장성을 위해서 이미지가 아닌 html로 구현해주세요!

2024-12-11 12:54 UTC, yeeuniii commented on src/main/resources/static/css/diary/write-page.css
> +}
개행 추가해주세요

2024-12-20 06:16 UTC, jisunggi commented
피드백 반영 후, 팁 메세지 랜덤으로 문구 뜨게 수정해주었습니다

2024-12-20 10:13 UTC, yeeuniii requested changes
피드백 반영 후 리뷰 재요청해주세요!

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/static/css/diary/write-page.css
> +    transform: translate(-50%, -50%);
transform 속성을 사용한 이유가 있나요?
top 만 조정해줘도 충분히 구현 가능해보이는데 아닌가요??

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/static/css/diary/write-page.css
> +.tooltip-text {
width 지정해주세요

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/static/css/diary/write-page.css
> +.tooltip {
얘도 width 지정해주세요

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/static/js/diary/write-page/write-diary.js
> +const textList = [
상수라면 대문자 변수를 사용해보는거 어떨까요

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/templates/diary/write-page.html
> +            <img src="/images/diary/write-page/tooltip.svg">
svg 파일말고 png 파일 사용 가능할까요?
svg 형식이 ios와 호환성이 좋지 않은거로 알고있어요!

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/templates/diary/write-page.html
> +            <div class="tooltip-text"></div>
text 요소인데 p 태그가 아닌 div 태그를 사용한 이유가 있나요?

저도 정확하게 아는 것은 아니지만 문자를 표현할때는 p 태그를 사용하고 있습니다!
[포스팅](https://inpa.tistory.com/entry/HTML-%F0%9F%93%9A-p-div-span-%ED%83%9C%EA%B7%B8-%EC%A0%95%EB%A6%AC)을 참고하면 좋을 거 같아요!!

2024-12-20 10:13 UTC, yeeuniii commented on src/main/resources/static/js/diary/write-page/write-diary.js
> +    tooltipText.textContent = textList[randomIndex];
innerText가 아닌 textContent 를 사용하신 이유는???

2024-12-20 17:59 UTC, jisunggi commented on src/main/resources/static/css/diary/write-page.css
> +    transform: translate(-50%, -50%);
텍스트 문구 크기가 고정되어 있지 않고, 길이에 따라 크기가 달라짐에 따라 top 만으로는 문구가 중앙 정렬 되지 않는 오류를 발견하였습니다. translate는 요소 크기가 동적일때 사용하고, 자기 자신의 크기로 고정되기때문에 이 경우에 사용하기 적합하다고 판단 하였습니다.

2024-12-20 18:01 UTC, jisunggi commented on src/main/resources/templates/diary/write-page.html
> +            <div class="tooltip-text"></div>
포스팅 내용을 참고해보니 텍스트는 <p>태그로 사용하는 것이 적절한 것 같아 수정하겠습니다!

2024-12-20 18:11 UTC, jisunggi commented on src/main/resources/static/js/diary/write-page/write-diary.js
> +    tooltipText.textContent = textList[randomIndex];
두개의 차이점을 정확하게 알지 못하였는데, 이번에 알게 되네요!
[innerText 와 textContent](https://hianna.tistory.com/483)
이부분은 해당 html 태그는 읽지 않아도 되고, 성능이 더 빠른 textContent 로 그대로 두었습니다.

2024-12-20 19:21 UTC, yeeuniii approved these changes
💯

2024-12-20 19:39 UTC, merged